### ISSUE TITLE
Enhancement Request - Remember Output Folder settings

### ISSUE THREAD

**Issue by DocJellyBean** [iPzard/mkvtoolnix-batch-tool#17]
This is a great app, thank you very much!

It seems that one has to specify the Output folder each time this app is started? It would be great if there could be an option to remember the selected Output folder, and the path be displayed in the Output folder box. That way the Output folder would already b specified when the app starts.

Thanks in advance for your consideration.

**Comment by iPzard** [comment]
Thanks for the enhancement suggestion! I'll take a look, but thinking it might be tricky or create unexpected behavior when used in conjunction with the "output same as source" option on the main page. 

Although maybe there's some middle ground, I do like the idea of creating an easier user-flow.. will take a closer look at this.

**Comment by DocJellyBean** [comment]
Thank you.

If I may ask a question here: what's the purpose of the **Merge** and **Remove** buttons under _Subtitle processing mode (merge selected)_?

**Comment by iPzard** [comment]
Yep, no problem! And about the different modes.. "merge" mode, which is the default mode, will merge subtitles into the video(s), "remove" mode will instead remove all existing subtitles from the video(s). There's also an option in the settings if you want to remove any existing subtitles before merging with merge mode.

**Comment by iPzard** [comment]
@DocJellyBean I think I figured something out for your feature request. Adding an option to "remember output directory, if same as source is not selected", in the settings. Should have a new release here shortly 🚀

**Comment by iPzard** [comment]
Thanks again @DocJellyBean , I just released [v2.1.0](https://github.com/iPzard/mkvtoolnix-batch-tool/releases/tag/v2.1.0) which includes your feature!

**Comment by DocJellyBean** [comment]
Thank you very much, looking forward to trying it out.
