### ISSUE TITLE
App doesn't launch on Windows Vista

### ISSUE THREAD

**Issue by MrSoul7** [iPzard/mkvtoolnix-batch-tool#19]
Hello Daniel

First of all....Thanks for your soft. ...it is what I dream to manage my TV shows mkv & subtitles
Unfortunately I have an old laptop on vista.... I installed your program.... but when I launch it => nothing happens 
Is it normal?
What is the minimum version of Windows for your soft?

Thanks

**Comment by iPzard** [comment]
Looking into your issue, I think I might see the cause. PyInstaller is used to bundle the Python scripts in a way where the user doesn't need to install Python, they offer [this notice](https://pyinstaller.readthedocs.io/en/stable/usage.html#windows) about Windows < 10. In short, it seems only Windows 10 is currently supported.

The solution for this appears to be to build the app on Windows 7, in which case PyInstaller will bundle the correct C++ distribution files. Though I'm guessing doing so on Vista will probably work the same way. Unfortunately, I don't have a Windows 7 _(or Vista)_ build of Windows to achieve this. However, if one becomes available I can make a build but not sure if/when that would be. 

In the meantime, you're welcome to create and install a build to try it out, here are the steps:

Ensure you have [Node](https://nodejs.org/en/download/) and [Python](https://www.python.org/downloads/) installed on your Vista pc, then clone this repository. After it's cloned, navigate to the project's root directory on your computer and run the following scrips in a terminal application (e.g., Git Bash):

`pip3 install -r requirements.txt`
`yarn install`
`yarn run build:package:windows`

From there, you can navigate from the project's root directory to `dist/windows/setup` to find and use the installable `.msi` file. I wish I could just spin up a build for you (and others needing this on < Windows 10), but hopefully this will at least get you up and running.

**Comment by MrSoul7** [comment]
Hello 

Thanks for your quick answer. I'm not sure to succeed to make it work with node and python adhoc packages.
The best option for me is to use a W10 build.
Thanks again.

Regards

**Comment by iPzard** [comment]
Ok, no problem. Sorry for the inconvenience.
