### ISSUE TITLE
Source directory folder gets deleted after process

### ISSUE THREAD

**Issue by DocJellyBean** [iPzard/mkvtoolnix-batch-tool#21]
The more I use this app, the more I like it :)

Let's say I have a folder named _Video Files_, and my videos and srt files are in that. Once the app has completed processing all the files, the source folder _Video Files_ gets deleted if the **Remove old video and subtitle files from source directory when finished** option is selected.

I don't know if this is a bug, or whether that is intended. IMHO the source folder shouldn't get deleted, as it could be a working folder.

**Comment by iPzard** [comment]
Thanks, I appreciate that! I appreciate the reports too, it really helps keep the software in top shape! 

So this should only happen when; after deleting the original files, the source directory is empty. That way the user doesn't have to delete the empty directory once everything is done. 

But if you experienced the source directory being deleted when it's populated with non-processed/old files (e.g., an extra image file you had in there), or when it's also the output directory, let me know.. that would be a bug I can look into.

**Comment by DocJellyBean** [comment]
No, the source directory doesn't get deleted if there are other files present. Which means that it works as intended.

No problem, I can always create an empty txt file or something in that directory to prevent it from getting deleted.

**Comment by iPzard** [comment]
I see, so you have a directory just for processing/input that you'd like to keep around even when processed files are deleted, so it's there for next time. I'll keep that in mind in case any ideas to satisfy both use cases come up.  

But in the meantime, any non-video, non-subtitle file should do the trick.. including a .txt file like you mentioned.
