### ISSUE TITLE
file extension merge error

### ISSUE THREAD

**Issue by im-gugogi** [iPzard/mkvtoolnix-batch-tool#22]
If the file name contains "." it is merged into one file

example:

input :
The One. S01E01.mp4
The One. S01E01.srt
The One. S01E02.mp4
The One. S01E02.srt

output : 
The One. S01E01.mkv (Include The One. S01E01.srt,The One. S01E02.srt)
The One. S01E02.mp4

**Comment by iPzard** [comment]
@minhonggu thanks for reporting this! I'll take a look into this shortly and update here.

**Comment by pannal** [comment]
Can confirm, this happens regardless of the SRT's name (tried adding ` English` to it, didn't change anything).

**Comment by iPzard** [comment]
@pannal Thanks for chiming in! But I think that would be a bit more error-prone, especially in cases where names are very similar. For example; Series.S01E01-1.something.mkv, Series.S01E01-2.something-else.mkv.. or Series.S01E01.something-part1.mkv, Series.S01E01.something-part2.mkv, would be problematic.

**Comment by pannal** [comment]
@iPzard Sure, that's managable, though. Either through a checkbox that enables this, or a warning if the app finds duplicates.

Would make quick merging quite a lot easier.

**Comment by iPzard** [comment]
@pannal Ok, I'll give it some thought 👍 

@minhonggu, @pannal It looks like there was an issue with the way the file name was being determined and separated from the extension. I was able to reproduce and fix the issue, the patch has been applied to [v2.1.2](https://github.com/iPzard/mkvtoolnix-batch-tool/releases/tag/v2.1.2). Gonna close out this ticket, thanks for the help everyone!
