### ISSUE TITLE
Feature Request: Support the same for audio tracks

### ISSUE THREAD

**Issue by Chaphasilor** [iPzard/mkvtoolnix-batch-tool#25]
So basically instead of merging in subtitles, do the same for audio files.

Bonus points if it could extract the audio from another video and merge it into the target somehow, but I guess that's a bit out-of-scope 😅

I'm not sure if this feature makes total sense, because it might be necessary to sync the audio (async audio is more of a problem than async subs)...

**Comment by iPzard** [comment]
Thanks for the request, I like the idea! Let me think on this one.. I think I want to add this but need to further review the scope of work involved.

**Comment by Chaphasilor** [comment]
Hey, so I actually already started working on this, but I used NodeJS instead of Python for the file system/mkvtoolnix interface.  
I also focused on automatically syncing the audio stream, by extracting the audio from an already synced video (normally you get secondary audio streams by downloading the whole video with the needed audio stream, so that should work well).  
I just don't know how this fits within the scope of your project 😅

If you're interested, let me know! I could publish the source code and maybe we can figure out a way to integrate it :)

**Comment by iPzard** [comment]
Nice! For this project I'd want to keep the logic in Python, instead of splitting it up between Node & Python.. but do you have a repo I can take a look at?

**Comment by Chaphasilor** [comment]
> Nice! For this project I'd want to keep the logic in Python, instead of splitting it up between Node & Python.. 

Sure, understandable :)

> do you have a repo I can take a look at?

Not yet, I'm working on it :)  
The basic concept is working with hard-coded filenames, I'm still trying to automate this and somehow entangle `ffprobe` with `mkvmerge` in a way that works reliably xD

But the basic concept right now is this:

1. Take two input videos. One is the "destination" (where you want the audio stream to be added to), the other one is the "source"
2. Find the offset between the two *videos* (currently involves some lengthy and performance-intensive work where video frames are compared for similarity). Now you know if one of the videos is ahead of the other one (like an extra intro, etc.)
3. Analyze the tracks of the source video to find the desired audio stream (e.g. certain language). Also check for any *additional* offsets between the video and audio tracks *within the source video* to compensate them before merging (this is the hard-coded part, because I haven't yet figured out how to match `ffprobe` streams to `mkvmerge` tracks...).
4. Calculate the total offset (between videos + between source tracks) and merge the audio stream into the destination file.  
   This of course could also work with multiple source audio streams with more or less zero additional overhead.

Finding the offset between the two videos takes around 30-45 seconds on my laptop, which isn't ideal but not a big deal when doing batch operations, I'd say.  
If you want to implement the audio track merging, but not the syncing, I could provide you with a CLI tool where you plug in two videos and it tells you the offset (which you could then optionally use).

**Comment by Chaphasilor** [comment]
@iPzard the repo is now public: https://github.com/Chaphasilor/video-sync

the readme still lacks a lot of information, but you can download the binary from the release page and use the `--help` command for some explanations :)  
If you start the binary without any arguments or flags it will also prompt you for everything.

If you want I could expose Node.js bindings for you to use (the logic would be in my library in that case), or you could call the binary from python...

**Comment by iPzard** [comment]
Nice! Was browsing through it and pretty cool so far!
