### ISSUE TITLE
Allow setting an intermediate destination for new files

### ISSUE THREAD

**Issue by seantcanavan** [iPzard/mkvtoolnix-batch-tool#28]
When working with HDDs, sequential access is paramount for performance. Therefore, reading from an input file and writing an output file to that same directory is counter productive for performance. Ideally, instead, users should be able to select an intermediate folder where temporary files are written to before being moved to their final destination.

E.G.

1. Read input file from remote HDD //nas/files/tv/show/s01/e01.mkv
2. Write new file to either another remote or local HDD: /home/user/Desktop/e01_new.mkv
3. Replace old file with new file: `mv /home/user/Desktop/e01_new.mkv //nas/files/tv/show/s01/e01.mkv

This method guarantees that all HDDs are either read or written to sequentially - hugely increasing their performance. Also, when working with remote targets, it can help alleviate network bottlenecks which are usually an issue when working with files over wifi as the intermediate file can be written locally before being moved back to the remote target.

**Comment by iPzard** [comment]
Let me think on this one.. this might overly extend the processing space and time, as it would need to copy/paste several files as well during the process. 4k movies are typically between 5-10GB, if processing even just 10 files that would equate to a much longer processing time since it would now need to copy/paste around 50gb on the low end.

**Comment by seantcanavan** [comment]
I think I misunderstood how your tool works or I worded my request poorly so I apologize.

When using `mkvmerge` - any changes are 'muxed' to a temporary file. To my knowledge there's no way to replace a file on the fly while also reading from it. This necessitates writing an entirely new copy of the original file during muxing before replacing the original.

The problem with this is that you're reading the input and writing the output to the same HDD which causes slowdowns. Quite the opposite of the longer processing time you're describing above,

Current scenario: 
`Client <-- read input & write output --> HDD1`

Better scenario: 
`Client <-- read input HDD1` 
`Client --> write output HDD2`

When done:
`move /hdd2/output.mkv /hdd1/input.mkv #replace original file with newly muxed file`

**Comment by iPzard** [comment]
No worries, what I'm referring to, and maybe I'm misunderstanding.. is an extra layer of processing space/time, so for example:

target (10gb) → destination (10gb)
target (10gb) → intermediate (10gb) → destination (10gb)

So in one case, 10 new GB are written.. in the other, 10 new GB are written and then copy/pasted. 

Personally, I don't think it's too much trouble to just select the intermediate as the destination directory, then manually copy/paste the final product. Not enough trouble to warrant adding it as a new feature at least.
