### ISSUE TITLE
Look into production and development builds for MacOS & Linux

### ISSUE THREAD

**Issue by iPzard** [iPzard/mkvtoolnix-batch-tool#34]
Currently python is using/referrencing the `mkvmerge.exe` file for CLI commands on line 29 and 30 of the `mkvtoolnix.py` file (link below).. Check if there are Linux & MacOS CLI packages for mkvmerge, if so.. add them to [./resources/mkvtoolnix](https://github.com/iPzard/mkvtoolnix-batch-tool/tree/master/resources/mkvtoolnix) and use the right one based on the OS.

Packaging scripts should omit any CLI packages not relevant for the OS they're packaging for.

https://github.com/iPzard/mkvtoolnix-batch-tool/blob/master/resources/modules/mkvtoolnix.py

**Comment by MilesTEG1** [comment]
Hello,
Dou you think you can make a macOS version?
