### ISSUE TITLE
Wrong Language Detection

### ISSUE THREAD

**Issue by Amir-Mohammed** [iPzard/mkvtoolnix-batch-tool#35]
If someone is trying to merge an Arabic subtitle, It would be detected as an English one

**Comment by iPzard** [comment]
Thanks for reporting this, would you mind providing the subtitle file you're having an issue with?

**Comment by Amir-Mohammed** [comment]
Thanks @iPzard for your quick reply. It's not just one file. My entire library of Arabic subs are doing the same, so I had to use another tool "JMkvpropedit" to edit subtitle headers. I'll attach you on of these subtitle file. Thanks.
[01.zip](https://github.com/iPzard/mkvtoolnix-batch-tool/files/6834061/01.zip)

**Comment by iPzard** [comment]
No problem, thanks for providing one of the files. I'll take a look and post back here.

**Comment by iPzard** [comment]
Looks like `.ass` files have some configuration information at the start of the file that needed to be ignored when parsing the text to automatically determine the file's language. 

I've fixed the issue, tests were successful using the file you provided. Here's a link to the new release:
[v2.1.4](https://github.com/iPzard/mkvtoolnix-batch-tool/releases/tag/v2.1.4)
