### ISSUE TITLE
Auto convert unsupported subtitle files (e.g., .smi) when merging

### ISSUE THREAD

**Issue by im-gugogi** [iPzard/mkvtoolnix-batch-tool#36]
**✨  Describe the feature**<br />
Typically, .smi files cannot be combined with .mkv
(automatically convert to .srt and merge)

- Should check if subtitle file is supported. If it's not, should attempt to [convert with ffmpeg](https://superuser.com/questions/1090989/changing-subtitle-format-with-ffmpeg).
- Should not leave new `.srt` file(s) in the user's directory(ies).. converted `.srt` files are deleted at the end of process.
- Temporary/converted `.srt` file(s) should have unique names to avoid naming conflicts _(e.g., {UUID}.srt)_. 
- Option to "Remove old video and subtitle files..." in settings should still work to remove the original (unsupported) subtitle files.

**Comment by iPzard** [comment]
Would it be possible for you to share a .smi file that you're having trouble with?

**Comment by im-gugogi** [comment]
https://www.capsubservices.com/assets/downloads/caption/SAMI%2000%20hour.smi

thank you

**Comment by iPzard** [comment]
No problem, thanks for reporting this! Been pretty busy lately, but will try to get to this sometime in the near future.

**Comment by iPzard** [comment]
Ok.. incorporated this feature in release [v2.2.4](https://github.com/iPzard/mkvtoolnix-batch-tool/releases/tag/v2.2.4), currently just includes support for `.smi` files, but it's built out in a way to easily include other file types if/when new support requests come through.
