### ISSUE TITLE
Automatically include font attachments

### ISSUE THREAD

**Issue by scese250** [iPzard/mkvtoolnix-batch-tool#37]
**✨  Describe the feature**<br />
Merge files from a folder called "attachments", for example. Or rather, detect fonts (.ttf, .otf, .ttc) on the root folder and merges it to the video. As optional, remove the all attachments existent from the input video.

**Additional context**<br />
Could be useful when working on anime series, because most of time you'll encounter to a lot of fonts to merge manually for each video.

**Comment by iPzard** [comment]
Seems possible in the [https://mkvtoolnix.download/doc/mkvmerge.html](MKVmerge CLI), which is what this tool uses. Are you able to share a .ttf, .otf, or .ttc file that I can work with? My thoughts are to make it follow the same logic as subtitles, where the name needs to match the video file.

**Comment by scese250** [comment]
Here is 3 different format fonts 

[Fonts.zip](https://github.com/iPzard/mkvtoolnix-batch-tool/files/6996714/Fonts.zip)

**Comment by iPzard** [comment]
Perfect, thanks! Got a lot going on atm, but will keep this on my radar and try to get to it in the near future. Thanks for the feature request too btw!

**Comment by iPzard** [comment]
I think I understand this a bit better.. so usually you'd have one set of fonts, like that ones provided, that you'd like applied to all mergeable videos _(valid video + subtitle exist)_ in that folder, and potentially videos that folder's sub-directories _(e.g., with an entire series/all seasons)_ during merge?

**Comment by Marco-9456** [comment]
Any Updates ?
