### ISSUE TITLE
Choose what subtitle to be removed when there is more than 1 Sub.

### ISSUE THREAD

**Issue by ZeroCool22** [iPzard/mkvtoolnix-batch-tool#41]
**✨  Describe the feature**
Lets say we have a video that have 2 Subs and we only want to remove 1 of them.

**Additional context**
Could add a choice to remove Subs by languaje.

Thx for the tool!

**Comment by iPzard** [comment]
Thanks for the feature request! Let me give this one some thought, trying to think of how to work something like this into the project. Makes sense though.
