### ISSUE TITLE
Malwarebytes warning about this program having Malware.

### ISSUE THREAD

**Issue by ZeroCool22** [iPzard/mkvtoolnix-batch-tool#42]
Here the screenshot.
![Screenshot_2](https://user-images.githubusercontent.com/13344308/131215542-1007f957-6f62-4ab5-b23d-c722fcc5a805.png)

**Comment by iPzard** [comment]
Will look into this, I'm guessing because it's an "unrecognized" program that manipulates local files. Ideally people are not getting this notice though, so hopefully a workaround.
