### ISSUE TITLE
Merging .srt

### ISSUE THREAD

**Issue by ShaniaP4in** [iPzard/mkvtoolnix-batch-tool#44]
**🦟 Describe the bug**
Your program work very good, fast and precis but i have a question

When opening the merged mkv in VLC i cant see any Language, only 1,2,3,4 etc

My mkv and srt have exact the same name like below, and the language that mkv merge use to determine country Norway ( no ) is in the srt file:

MyMovie.mkv
MyMovie.no.srt

So my question, do the srt file need to be renamed to MyMovie.Norwegian.srt for it to work
if yes maybe it need to follow ISO 639-1 Code    https://www.loc.gov/standards/iso639-2/php/code_list.php

Tnx in advance

**Comment by iPzard** [comment]
Hey @ShaniaP4in, thanks! There's no need to update the file name, this program automatically detects the subtitle language and applies it to the subtitle data when adding. However, it's not added to the subtitle's track name.. though it does use the language to check against your default language (in the program's settings) to determine if the subtitle should be the default subtitle used, in the event multiple subtitle files are added. 

Here's the source code for where it happens:
https://github.com/iPzard/mkvtoolnix-batch-tool/blob/d8a45e6f1a5c6e3004eedfe04dcd445b920b7010/resources/modules/mkvtoolnix.py#L97
