### ISSUE TITLE
Extract all subtitles from mkv files

### ISSUE THREAD

**Issue by ElimGarak72** [iPzard/mkvtoolnix-batch-tool#46]
**✨  Describe the feature**
Hello and thanks again for this wonderful tool.

Would it be possible to add a function that extracts the subtitles from all mkv files in a folder and puts them in the same folder with the correct names (same as the video)?

Thank you!

**Comment by iPzard** [comment]
This feature seems like a good idea, I don't think it would be too hard to add either. That said I'm not sure exactly when I'd have time, with the holidays around the corner there's a lot going on.. but sometime in the near future I can look deeper into getting this added.

**Comment by Rayman24365** [comment]
I wholeheartedly agree with this feature request. Extracting subs enables the user to then re-add only the subs of their choice. I feel this should be a very important part of this most excellent and unique piece of software.

Adding to that, the software would (most likely) be able to tell the language from the video file and could then add a distinct tag to the sub filename that makes the software recognize the language again upon re-adding it, just to prevent any miss-tagging of languages.

I've wanted this piece of software for a long time. I'll donate.

**Comment by iPzard** [comment]
The language of the subtitle file(s) may differ from the video file, but the text in the subtitle file can be parsed to determine the language automatically.

**Comment by iPzard** [comment]
@Rayman24365, I got this working locally.. created a pull request (link below) for anyone who wants to check it out. Should be able to push a release as soon as I run a few tests to make sure no new bugs are introduced. 

https://github.com/iPzard/mkvtoolnix-batch-tool/pull/72

**Comment by iPzard** [comment]
There were a few issues but got everything sorted out, merged in my latest changes and published a release, you can get the latest here:
https://github.com/iPzard/mkvtoolnix-batch-tool/releases

**Comment by Rayman24365** [comment]
Hello, I am getting errors during extracting subs with v2.5.1, also with previous versions.
I have tried as little as a simple folder d:\t with a single .mkv containing 2 subs.
Currently there is no function to remove all but one or two languages, but just to extract and then reintegrate the desired subs.
But extracting the subs I get "There was an error which prevented the batch from being processed".
I do not know what else to try to troubleshoot.
Cheers.

**Comment by iPzard** [comment]
Is it a video that you're able/allowed to share? If so I can take a closer look. My guess is the subtitle type is something not easily convertible to .srt, which is currently the only supported output type. I don't mind trying to fix that though.

**Comment by ElimGarak72** [comment]
> It is actually basic .srt I'm trying to extract. It happens with 100% of the files of vastly varying origin. The files and folders are accessible as I can remove the subs just fine, but extracting doen't work. Is there a debug switch that can tell me what error it is encountering?

Hi! By chance, are you trying dragging the folder into the interface? Or copying the address and pasting it in the "Source directory" field? I am asking because I have often issues like yours when I do that. My "solution" is to press the "Browse..." button and navigate to the folder. I don't know if it's the same for you, but I guess it's worth a try. ^_^

**Comment by Rayman24365** [comment]
No, I select the folder through the standard Browse buttons. Tried using different folders and a single folder on various drives.
It works when removing subs, but extracting gives these error messages.
I tried it on another machines as well, same result. I'm stumped.

**Comment by iPzard** [comment]
Yea, weird SRT should be fine.. are you able to share any of the videos you're having issues with so I can take a look?

**Comment by iPzard** [comment]
I might have fixed the issue in the latest release, if not the debug option and error logs are included in that release too. 
https://github.com/iPzard/mkvtoolnix-batch-tool/releases
