### ISSUE TITLE
Functions to add to cleaning of subtitles

### ISSUE THREAD

**Issue by ElimGarak72** [iPzard/mkvtoolnix-batch-tool#47]
**✨  Describe the feature**
Hello! Could it be possible to add the following optional functions to the cleaning of the subtitle?

- Strip text between parentheses ( )
- Strip text between curly brackets { }
- Strip text between angle brackets < >
- Strip text between square brackets [ ]
- Strip text between asterisks * ... *
- Strip any cue containing a music note (♪)
- Strip speaker labels
- Fix two line subtitles with an empty line in the middle
- Fix all-uppercase subtitles

Thank you!

**Comment by iPzard** [comment]
This would be more difficult than it seems on the surface.. there are a plethora of supported subtitle files, some process information differently than others and may even have valid instances of these occurrences in the file's configuration section (for subtitle files which have one).. so parsing the data in SRTs for example, to incorporate these features may work great, but for another file type could be rendered incompatible after satisfying one of the above conditions. 

Another thought is oftentimes these characters and sets are included for additional functionality or context with subtitles. I would recommend finding a more appropriate version of the subtitle that meets your preferences. Although I know this might be easier said than done in a large library of files.
