### ISSUE TITLE
can you add language option on the video?

### ISSUE THREAD

**Issue by post-master** [iPzard/mkvtoolnix-batch-tool#48]
**✨  Describe the feature**
Thanks for this wonderful tool. but can you add language option on subtitle and audio files? when I merge with "MKVTOOLNIX" I can see the language tag when I check the media info. but after emerging with this tool language option not available for any subtitle and audio. can you add this feature please ?

**Comment by iPzard** [comment]
Thanks for the feedback, unlike MkvToolNix GUI, there is no need to set the language with MKVToolNix Batch Tool. With this tool, the text from each subtitle is examined and the language is determined automatically. 

Here's the code where it happens..
https://github.com/iPzard/mkvtoolnix-batch-tool/blob/d8a45e6f1a5c6e3004eedfe04dcd445b920b7010/resources/modules/mkvtoolnix.py#L152

It would actually create issues if the language was set manually.. for example, a user who speaks multiple languages who wants to batch convert a library containing multiple languages.

**Comment by post-master** [comment]
> Thanks for the feedback! Unlike MkvToolNix GUI, there is no need to set the language with MKVToolNix Batch Tool. With this tool, the text from each subtitle is examined and the language is determined automatically.
> 
> Here's the code where it happens..
> 
> https://github.com/iPzard/mkvtoolnix-batch-tool/blob/d8a45e6f1a5c6e3004eedfe04dcd445b920b7010/resources/modules/mkvtoolnix.py#L152
> 
> It would actually create issues if the language was set manually.. for example, a user who wants to batch convert a library containing multiple languages.

sir it can not determine the language automatically. check again, please. it just remove the language option from subtitle and audio

check the subtitle section on the media info. the same file merged without any optional changes.

mkvtoolnix-batch-tool media info: https://pastebin.com/QaWvznF6

MKVToolnix  GUI media info: https://pastebin.com/EXMKyX2g

**Comment by iPzard** [comment]
If you're merging a subtitle file(s) and it's not setting the language correctly, feel free to open a "bug" ticket for that including the subtitle file you're having issues with and I can take a look.

 In my last message, I sent a link to where the language determination happens in the codebase. Feel free to take a look if you'd like, that functionally has been tested and verified for some time now.
