### ISSUE TITLE
Allow for overrides in language and default track settings via subtitle file naming convention

### ISSUE THREAD

**Issue by iPzard** [iPzard/mkvtoolnix-batch-tool#51]
**✨  Describe the feature**
[Currently](https://github.com/iPzard/mkvtoolnix-batch-tool/blob/d8a45e6f1a5c6e3004eedfe04dcd445b920b7010/resources/modules/mkvtoolnix.py#L92) all subtitle files of default language be flagged as the default. This can create unexpected behavior for the end-user. There are also issues when TextBlob and the underlining Google Translate API are unable to translate a particular file, in this case it would be convenient for end-users to have an option to manually set/force the language. 

It was discussed in [Issue 55](https://github.com/iPzard/mkvtoolnix-batch-tool/issues/55) that appending `.forced` to mirror the behavior w/Plex and other tools may be helpful. Especially considering users with such tools may have already renamed their files. 

This request includes the following:

- Allowing subtitles to use `.forced` or `.default` to force them in as the default track. (e.g., "filename.forced.srt" or "filename.default.srt") in the event multiple subtitle files of the same (default) language exist.
  - Should also implement additional features mentioned in [Issue 55](https://github.com/iPzard/mkvtoolnix-batch-tool/issues/55).
- Allowing language to be set with an ISO 639-1 code _(e.g., "en", "nl", "fr", etc..)_ added to the end of the filename. This should override any potential detected languages, to allow for overrides in the event an incorrect translation was made. 
- Allowing multiple naming convention options to be set at once (e.g., "filename.en.forced.srt" or "filename.forced.en.srt").
- Updating the readme to explain this new functionality.

**Comment by gleep23** [comment]
Heya. This app is a huge time saver, thanks very much. It works very well some of the time.
I'm getting mixed success with identification of languages on some specific files, and I cannot figure out why they are responding differently. 
All my srt files are in English, they get identified as German, Vietnamese and a few Swahili.
I've spent a few hours testing all sorts of combinations of MKVToolNix Batch Tool features, and renamed files all sorts of names.
For further testing, I've used the srt files on other videos, and I get the same misidentification.  I've used alternative srt files on the same videos, and get no errors. 
Can you have a look at my srt files, and see if you can spot what might be going on?
See attached: [subtitle_language_errors_2022-03-04.zip](https://github.com/iPzard/mkvtoolnix-batch-tool/files/8183341/subtitle_language_errors_2022-03-04.zip)

I am running Windows 10 Pro 21H2 x64 (English) (not English International), all my Windows language settings are English (Australian) [en_au]. I also have the language packs installed for English (United Kingdom) [en_gb], and English (United States) [en_us]. I've got MKVToolNix v65.0, mkvmerge v65.0, MKVToolNix Batch Tool v2.3.1. I can supply further technical details upon request.

**Comment by iPzard** [comment]
> Heya. This app is a huge time saver, thanks very much. It works very well some of the time. I'm getting mixed success with identification of languages on some specific files, and I cannot figure out why they are responding differently. All my srt files are in English, they get identified as German, Vietnamese and a few Swahili. I've spent a few hours testing all sorts of combinations of MKVToolNix Batch Tool features, and renamed files all sorts of names. For further testing, I've used the srt files on other videos, and I get the same misidentification. I've used alternative srt files on the same videos, and get no errors. Can you have a look at my srt files, and see if you can spot what might be going on? See attached: [subtitle_language_errors_2022-03-04.zip](https://github.com/iPzard/mkvtoolnix-batch-tool/files/8183341/subtitle_language_errors_2022-03-04.zip)
> 
> I am running Windows 10 Pro 21H2 x64 (English) (not English International), all my Windows language settings are English (Australian) [en_au]. I also have the language packs installed for English (United Kingdom) [en_gb], and English (United States) [en_us]. I've got MKVToolNix v65.0, mkvmerge v65.0, MKVToolNix Batch Tool v2.3.1. I can supply further technical details upon request.

Hey @gleep23, thanks for reporting this! Would you mind opening up a [Bug ticket](https://github.com/iPzard/mkvtoolnix-batch-tool/issues/new?assignees=iPzard&labels=bug+%F0%9F%A6%9F&template=bug_report.md&title=) for this so it can be tracked and worked on separately from this current ticket?

**Comment by mervincm** [comment]
strangely I also see the same errors. everything I have is English, yet in merge, it tags the language on occasion as Vietnamese or german.

**Comment by iPzard** [comment]
> Heya. This app is a huge time saver, thanks very much. It works very well some of the time. I'm getting mixed success with identification of languages on some specific files, and I cannot figure out why they are responding differently. All my srt files are in English, they get identified as German, Vietnamese and a few Swahili. I've spent a few hours testing all sorts of combinations of MKVToolNix Batch Tool features, and renamed files all sorts of names. For further testing, I've used the srt files on other videos, and I get the same misidentification. I've used alternative srt files on the same videos, and get no errors. Can you have a look at my srt files, and see if you can spot what might be going on? See attached: [subtitle_language_errors_2022-03-04.zip](https://github.com/iPzard/mkvtoolnix-batch-tool/files/8183341/subtitle_language_errors_2022-03-04.zip)
> 
> I am running Windows 10 Pro 21H2 x64 (English) (not English International), all my Windows language settings are English (Australian) [en_au]. I also have the language packs installed for English (United Kingdom) [en_gb], and English (United States) [en_us]. I've got MKVToolNix v65.0, mkvmerge v65.0, MKVToolNix Batch Tool v2.3.1. I can supply further technical details upon request.

I was able to reproduce and fix this with the files provided, I was evaluating each word rather than each sentence in the language detection process. I updated to check each sentence and it consistently comes back as English. I'll have an update for that included when this issue is complete. 

cc @mervincm

**Comment by iPzard** [comment]
I just added this feature in the [latest release](https://github.com/iPzard/mkvtoolnix-batch-tool/releases). There's additional information in the [readme](https://github.com/iPzard/mkvtoolnix-batch-tool#readme) now about it too _(see below)_. 

![image](https://user-images.githubusercontent.com/8584126/220043567-beaa3ca6-31d9-4206-b2cf-08fcd5b77eda.png)

Let me know if you run into any trouble.

**Comment by mervincm** [comment]
Working well!
