### ISSUE TITLE
When trying to merge the smi files, the video is deleted and does not merge

### ISSUE THREAD

**Issue by im-gugogi** [iPzard/mkvtoolnix-batch-tool#52]
**🦟 Describe the bug**
When trying to merge the smi files, the video is deleted and does not merge.

**Steps to Reproduce**
Try to merge mkv and smi files.

**Screenshots**
https://i.imgur.com/t9mfocR.gif

**Additional context**
sample video and .smi subtitle : https://drive.google.com/file/d/1-iUoIUEv8zdmCkbmp1crHefwCbwICdu-/view?usp=sharing

thank you

**Comment by iPzard** [comment]
Are you using the most recent version? I was able to merge the provided files w/o any issues. If you are using the latest version, are there any other steps you can think of to help reproduce the issue?

**Comment by iPzard** [comment]
And as always, I really appreciate you reporting this unexpected behavior!
