### ISSUE TITLE
Keep/Reuse SRT SDH and FORCED attributes

### ISSUE THREAD

**Issue by jfreiman** [iPzard/mkvtoolnix-batch-tool#55]
I want to be able to merge multiple srt files which contain the type of subtitle they are after being merged.  The ultimate goal is to output video files (mostly tv series) with the endpoint being used on my Plex Server.

**Filename examples**
video.mkv
video.eng.srt (standard subtitles)
video.eng.sdh.srt (hearing impared)
video.eng.forced.srt (forced)

Currently, when using your app with the file names above, it merges all 3 srt files into the mkv, but it names them 01, 02, and 03 and does not set either the forced flag or the Hearing Impaired flag.

If this can't be accomplished and/or is not within the scope of this project, perhaps you could create a default naming scheme for the merged srt files -

01 - standard
02 - SDH
03 - forced

I don't know, there might already be a standard srt naming scheme already that I'm not aware of that could be more beneficial for others.

Thank you for considering adding this feaure.

**Comment by iPzard** [comment]
Thanks for reporting this! Yea, this is something I can take a look at, it's a good idea.. not sure exactly when, but I preserved the issue so stalebot doesn't remove _(set to wontfix)_ it again.

**Comment by ChaoticHolon** [comment]
I am having this exact same issue. Thank you for looking into this, and I am looking forward to a solution!

**Comment by iPzard** [comment]
Going to address this in [Issue 51](https://github.com/iPzard/mkvtoolnix-batch-tool/issues/51), since it's very similar and works in the same area.
