### ISSUE TITLE
Add subtitle Name and Language

### ISSUE THREAD

**Issue by Yusseiin** [iPzard/mkvtoolnix-batch-tool#56]
The tools work really well, is it possible to add the possibility to choose the language of the subtitles and the name of the subtitle?

When you open the mkv the subtitle is called 01/02/03 and no language is specified it is a bit difficult to choose the right one.

**Comment by iPzard** [comment]
There might be a way to fix this while addressing https://github.com/iPzard/mkvtoolnix-batch-tool/issues/51, I'll close this ticket, since it's being worked on there.. feel free to add any additional input there as well.
