### ISSUE TITLE
set default language track to chinese  but out to korean

### ISSUE THREAD

**Issue by ircopdd** [iPzard/mkvtoolnix-batch-tool#59]
![2022-05-27_191939](https://user-images.githubusercontent.com/3633003/170690447-bb5c9d9d-74f9-42ac-85f0-02e2d31bb2a3.png)
![2022-05-27_192351](https://user-images.githubusercontent.com/3633003/170690478-5203748b-505e-4b98-9b8e-b5e0f3fedb81.png)

**Comment by iPzard** [comment]
Thanks for reporting this! Would you mind providing a copy of the subtitle file you're having an issue with?

**Comment by ircopdd** [comment]
> Thanks for reporting this! Would you mind providing a copy of the subtitle file you're having an issue with?

[Delicacies.Destiny.E01.2022.zip](https://github.com/iPzard/mkvtoolnix-batch-tool/files/8792446/Delicacies.Destiny.E01.2022.zip)
