### ISSUE TITLE
Persian Language Support

### ISSUE THREAD

**Issue by PHM2D** [iPzard/mkvtoolnix-batch-tool#60]
Hi,
this is a huge time saver tool absolutely useful.
It would be much better if it supports Persian language (per/fa) as well.
And if possible, please add more dark themes.
Thank you.

**Comment by iPzard** [comment]
Good suggestions, thanks! Will take a look, but might take a while till I have some time.

**Comment by iPzard** [comment]
Looks like Persian is already supported as of [v1.1.1](https://github.com/iPzard/mkvtoolnix-batch-tool/releases/tag/v1.1.1), [here](https://github.com/iPzard/mkvtoolnix-batch-tool/blob/f58a9ba08ae30dec105be9632726868997651eec/resources/modules/mkvtoolnix.py#L476) is the line where it's added. 

You can try with the latest version (below), if you continue to have issues feel free to re-open the ticket or start a new one. 
https://github.com/iPzard/mkvtoolnix-batch-tool/releases
