### ISSUE TITLE
English default track - have two English track.. 

### ISSUE THREAD

**Issue by yanz** [iPzard/mkvtoolnix-batch-tool#67]
My files have jap and 2 version of English dubb.   
  
Could you implement a way to list the actual audio tracks with each a tick for "default track"  
  
Also if possible add option to remove a track entirely as well please.   
  
Very neat tool thank you

**Comment by briantho** [comment]
> My files have jap and 2 version of English dubb.
> 
> Could you implement a way to list the actual audio tracks with each a tick for "default track"
> 
> Also if possible add option to remove a track entirely as well please.
> 
> Very neat tool thank you

I would like this feature as well. It would be nice if more than one language is detected, or if there are multiple English subtitles to present a dialog or something saying which tracks you want. This could be done globally by language, by batch job, or per file.
