### ISSUE TITLE
VTT subtitle support

### ISSUE THREAD

**Issue by Coolie2** [iPzard/mkvtoolnix-batch-tool#70]
While I've been able to successfully merge SRT subtitles so far, VTT subtitles appear not to be supported. Given that MKVToolNix itself appears to support them, successfully merging them when manually combined, could the subtitle format be added to the batch tool?

**Comment by iPzard** [comment]
Might be an easy update, I can take a look.. do you have a `.VTT` subtitle file I can use for this?

**Comment by Coolie2** [comment]
Here's a video of my own and the VTT subtitles YouTube auto-generated for it as an example: https://drive.google.com/drive/folders/1ThjxwcbtYGf9LfexMagQiykyfgDGJzV9?usp=sharing. Unlike the other site I found VTT subtitles on, YouTube seems to also integrate them directly into the MP4 file, so while in this case combining the VTT file with the video results in two seemingly identical subtitle tracks, in other cases VTT subtitles aren't automatically built-in, as far as I can tell.

**Comment by iPzard** [comment]
Nice, thanks for the example file, will take a look at this shortly! Hopefully it's a quick update.

**Comment by iPzard** [comment]
Sweet, looks like MKVToolNix knows how to process this under the hood so it was an easy [change](https://github.com/iPzard/mkvtoolnix-batch-tool/pull/73). They should be supported now in the latest release:
https://github.com/iPzard/mkvtoolnix-batch-tool/releases

**Comment by Coolie2** [comment]
Thanks!
