### ISSUE TITLE
Source folder deleted when "Remove old video and subtitle files..." selected and SRC and DST folders different

### ISSUE THREAD

**Issue by jcouch93** [iPzard/mkvtoolnix-batch-tool#71]
**🦟 Describe the bug**
v2.3.1 on Win10
Source and Dest Dirs are different (both are on remote paths, i.e Source is on \\Server\Input\Subtitle_Merge and Dest is on \\Server\Output\Subtitle_Merge)

All options checked

**Steps to Reproduce**
Add MKV and sub file to SRC folder
Verify all options checked and SRC and DST folders are present
Verify mode is Merge
Click Merge button
Files are merged and a single file is placed in DST folder
Source files are deleted, but SRC folder is also deleted

**Expected behavior**
Files will be merged and source files will be deleted but SRC folder will still be present

**Screenshots**

**Additional context**
If option "Remove old video and subtitle files..." isn't selected SRC directory isn't deleted
If "Output same as source" is checked then SRC folder isn't deleted

**Comment by iPzard** [comment]
This is expected, it only deletes the parent folder if it's empty after the old files are removed from it.
