### ISSUE TITLE
Add option to set subs with forced display flag

### ISSUE THREAD

**Issue by kstorbakken** [iPzard/mkvtoolnix-batch-tool#74]
**✨  Describe the feature**
A clear and concise description of the feature you want.

In MKVToolNix, there is an option to set any selected track as forced display. For subtitle files, this is usually used when there's only subs for foreign parts and your library is focused on supporting a single language. It's helpful in certain media players that look for this flag and otherwise default to the subs being disabled. If you always want subs displayed regardless of the language, it's usually a good idea to have this flag set too. 

**Additional context**

I'm using this tool regularly and noticed this would help me a lot. Right now I'm just leaving the tracks I want forced displayed as-is (not forced) after running them through this batch tool. If there was a way to go back through previous mkv files and batch process them to force enable all subtitle files (not adding or removing any tracks), that would be very helpful as well.

**Comment by iPzard** [comment]
Good timing, I just added this feature in the [latest release](https://github.com/iPzard/mkvtoolnix-batch-tool/releases). There's additional information in the [readme](https://github.com/iPzard/mkvtoolnix-batch-tool#readme) now about it too _(see below)_. 

![image](https://user-images.githubusercontent.com/8584126/220043567-beaa3ca6-31d9-4206-b2cf-08fcd5b77eda.png)

Let me know if you run into any trouble.
