### ISSUE TITLE
Drag and drop folder to set source directory

### ISSUE THREAD

**Issue by Andrew247365** [iPzard/mkvtoolnix-batch-tool#8]
It would be convenient if it was possible to drag and drop a folder into the program window to set a new 'source directory'.

Thank you VERY much for this program, I am not a coder and don't understand how to use the various scripts I found while trying to google a solution to this. This program is so useful.

**Comment by iPzard** [comment]
Glad you like it! Yea, a little busy with the holidays at the moment, but I can look into adding drag and drop functionality. I'll update this ticket to keep you in the loop, either when it's done or if there's something that prevents this functionality.

**Comment by iPzard** [comment]
Alright buddy, you're all set! Drag & drop functionality for source directory selection is available starting with v2.0.2 in the [downloads section](https://github.com/iPzard/mkvtoolnix-batch-tool/releases). 

Luckily it was less than 10 lines of code, so ended up being a pretty easy update. Let me know if you run into any issues, thanks again for the great suggestion!
