### ISSUE TITLE
Remove all subs but one specific language, maybe main program language

### ISSUE THREAD

**Issue by Rayman24365** [iPzard/mkvtoolnix-batch-tool#80]
A feature where all subs are removed except for subs from one (or two) specific language which is retained.

The main screen dropdown menu could have an additional option where besides 'remove' there could be a 'only retain *** subs' option. The asterisks could then be replaced by either the main program set language or a separate drop down box chosen language (preferable) in the settings menu.

Optionally for dual lingual people two language drop down boxes so that besides the original language of the file also a second (native?) language of choice can be chosen.

Many video files have a plethora of subs, 40 or more sometimes when some people would only like to retain the English subs or maybe an extra one if their native/ethnic language is in there too.

**Comment by iPzard** [comment]
Let me give this one some thought, I'll have to double-check how the `remove` process operates behind the scenes to see what kind of work this would require. 

For UI, my thought would be if/when `remove` mode is selected, a new dropdown appears with checkable (checkboxes) options for any languages to keep.. then it remembers them like other settings, so you don't have to check them every time you use the `remove` option.
