### ISSUE TITLE
Error:: There was an error which prevented the batch from being processed.

### ISSUE THREAD

**Issue by pm0code** [iPzard/mkvtoolnix-batch-tool#82]
**🦟 Describe the bug**
The title says what it is.

**Steps to Reproduce**
1. Select source dir with a bunch of video files plus corresponding .srt files
2. Select the output directory
3. click on merge
4. See the error

**Expected behavior**
parse through the files and merge them as it used to do before. something broke something somewhere with an update.

**Screenshots**
![image](https://user-images.githubusercontent.com/126919917/222839834-da565d76-a569-4096-91c8-6f33077554d3.png)

**Additional context**
This used to work flawlessly and was broken somewhere along the line with one of the updates.

**Comment by iPzard** [comment]
Thanks for sharing this! Just curious, which version are you on currently? You can see the version if you go to add/remove programs in Windows and view the app. The latest version, [v2.5.4](https://github.com/iPzard/mkvtoolnix-batch-tool/releases/tag/v2.5.4), was pushed today which might resolve the issue. 

If not, there are some extra steps we try to resolve this. Depending on the version, there may also be some error logs in `%appdata$/MKVToolNix Batch Tool/error.log`, if so would you mind sharing them? If you can share the subtitle you're having issues with, that may be helpful as well.

**Comment by pm0code** [comment]
Hi, I believe that our actions crossed, as at the same time that I posted this, you had posted an update which I then downloaded and tested and that fixed the issue. Thank you for that.
As a suggestion, you may want to consider printing the version on the title panel, just like how MKVToolnox does. please see the screenshot. 
![image](https://user-images.githubusercontent.com/126919917/222989585-62915b16-dd21-4ce8-9fb8-541977a42e0b.png)

Second, you may want to consider a button to load the logs in notepad, somewhere in your UI, perhaps under the settings.
Third, you may want to consider an option to set subs properly in the output MKV file. 
Use case: there could be at least two sub-files, one that is the default full eng sub and then another that is the FORCED subfile. they are both in eng, but need to have different flags in the MKV file to be properly displayed.

Once again, I appreciate your work.

**Comment by iPzard** [comment]
Thanks for the suggestions, these are great ideas! I created new [tickets](https://github.com/iPzard/mkvtoolnix-batch-tool/issues) for both of them.

For your subtitle delema.. those should be auto detected, one thought is the settings have a default language, which now defaults to None but used to default to your language (guessing English). If you update that to none, newly merged subtitles will not be set to default. 

There's also a new features to both extract subtitles and override settings using file naming conventions. So in this case, you can extract the subtitles, then update their names to remove `.default` and/or `.forced` then re-merge them. Hope that helps!

**Comment by pm0code** [comment]
Excellent and thanks fro considering them.
I will continue using your tool and provide feedback as I come across anything.
Please feel free to ping me if you need a Beta tester.
