### ISSUE TITLE
[Error Handling] Provide better notices and create .log file(s) to assist with troubleshooting

### ISSUE THREAD

**Issue by Highlander009** [iPzard/mkvtoolnix-batch-tool#9]
I installed v2.02 and it worked beautifully a couple of times but now I constantly get an error and the batch processing fails with no mp4/srt files muxed!

Can you improve error reporting such that it states what has caused the error?  I have no idea why it no longer works for me; I have tried various alterations to the files but nothing works and it would be really helpful if the program stated WHY it was failing.

Thanks.

![2020-12-08](https://user-images.githubusercontent.com/75662406/101452351-7ab22300-3925-11eb-8e7a-d2fc497985b3.png)

**Comment by iPzard** [comment]
Thanks for using the app and reporting this! The most common errors provide a more descriptive message, the generic one you received is a fallback, but I can look into getting that updated so it's more clear as to what happened. 

Would you mind sharing what the directory structure looks like, including the file extensions? An easy way to export the directory structure to a .txt file using command prompt is `dir > directory.txt`.

Another thing to check, which I can't see from the directory structure alone, is are the .srt file(s) are valid? In other words, do they contain readable text when you open them? If that happens to be the case, still let me know.. I'd still want to update the error message to explain that if so.

**Comment by Highlander009** [comment]
Hi,

Thanks for your reply.  Unfortunately, I don't think the problem is as simple as the directory structure or file integrity.  I'm happy to attach (below) a directory listing and also what "dir > directory.txt" produced.  The .srt files are all valid files (as are the .mp4 videos); opening any of the video files in VLC they display correctly and the subs al display perfectly.

I'm running Win 10 Pro on a 250Gb SSD with MKVToolNix v51 installed.  Could there be some incompatibility there?  There is a "Tb HDD attached and anothe 500 Gb HDD all connected to MoBo. Another two HDDs are connected via USB.  I have tried moving files arouind these different locations in several attempts to get the program to work.

As I said, it worked perfectly on a folder with a few files in it  and a second time on a folder with a sub-folder included (to test the recursioon) but as soon as I tried to run it on the large, 28Gb Dr. Who folder  (containing all 12 series in their own folders of 10-12 videos plus a 'Specials' folder containing around 20 videos) I started to get the error message.

To give you a directory listing I cereated a copy of the Series 11 folder on my Desktop and another empty folder as a destination but this time I couldn't even get your program to start!  It simply wouldn't respond at all to attempts top start it so I uninstalled it and re-installed it.  Having re-installed it I tried to mux the files in the Series 11 folder but jst got the same error message again,

Perhaps it might be possible to write a log file that captured each step in the process as your progam runs.  Examination of that might throw up the step at which the execution fails and reveal what it can't handle?

I'll be very interested to read any further comments you might have.

Thanks
[Doctor Who Series 11.pdf](https://github.com/iPzard/mkvtoolnix-batch-tool/files/5659415/Doctor.Who.Series.11.pdf)
[directory.txt](https://github.com/iPzard/mkvtoolnix-batch-tool/files/5659417/directory.txt)

**Comment by Highlander009** [comment]
Typos (my bad):-

Para 1:  "subs al display perfectly" should read:  "subs all display perfectly"

Para 2:  "There is a "Tb HDD attached and anothe 500 Gb HDD all connected to MoBo" --> "There is a 2Tb HDD attached and another 500 Gb HDD all connected to the MoBo"

Para 3: "to test the recursioon" -->"to test the recursion"

Para 5: "log file that captured each step" --> "log file that captures each step"

(I should have checked the 'Preview' before posting but I've only just realized that facility exists, :))

**Comment by iPzard** [comment]
Cool that's perfect, thanks. Looks like your files are all correctly structured. I don't think your computer setup or MKVToolNix v51 will make a difference, this program has it's own mkvmerge.exe to run commands off of to ensure consistency there. I'm wondering if there's an issue with the encoding or something of one of the subtitle files, or possibly hidden files/folders confusing the program or something. I really like your idea about generating an error log in the event of an error (especially "generic" ones like this one), I think a lot of other software does that too, seems like good practice. 

I'll add the "create error log" functionality in a v2.0.3 shortly and update here when that's available so we can continue to troubleshoot this. I'll try to play around with a few things too and update here if any suggestions come to mind. If you really want to get your stuff merged asap you can try folder/season at a time, might help narrow down the problem(s) too.

**Comment by Highlander009** [comment]
I found a restore point that was just before I installed your program so I rolled back the system hoping that reinstalling it after that would allow it to work (like it did after the very first install),  After I'd cleaned everything up and created a new restore point, I reinstalled it.  One thing, on first run I get the Security Alert shown (is that to be expected?).

![2020-12-08 (4)](https://user-images.githubusercontent.com/75662406/101519165-c2af6500-397a-11eb-9879-788a65abed83.png)I 

I just clicked "Allow" to proceed and set Source to The Series 11 folder again (now residing on an external HDD via USB) but when I tried to drag a Destination in it won't allow that!  Instead it opens a load dialogue (that defaults to "Documents" folder so I'm forced to navigate to a Target folder (but just chose to tick output same as source instead)

![2020-12-08 (6)](https://user-images.githubusercontent.com/75662406/101519950-b4157d80-397b-11eb-8f47-123b3a91a036.png)

However, when I click Merge it **_starts_** to run....

![2020-12-08 (8)](https://user-images.githubusercontent.com/75662406/101520613-a7ddf000-397c-11eb-8861-12f82bcf8e60.png)

but as soon as it displays 1 of 10, it stops and the error message comes up again!

![2020-12-08 (7)](https://user-images.githubusercontent.com/75662406/101522952-d7422c00-397f-11eb-9291-ec70a64af681.png)

So it looks like it just ain't gonna run on my machine!   So annoying, especially since I got it to do what I want for a couple of runs just after the very first install and I have so many goddam TV shows that I want to mux the subs into so I can watch them comfortably (I'm deaf as a post! lol) and I just don't have the time (or patience) to sit and run them all through the MKVTool.GUI individually!  I don't suppose you have a short batch (.bat) file that would recursively mux .srt to .mp4, ideally saving the .mkv files from the Source to a Target folder and setting the subs as Default, English & Forced, with chapters included at fixed (300s?) intervals and also inserting 2 or 3 Spaces into the File Title field.  In other words just exactly what your program does! lmao (but with a few enhancements you might want to consider adding into future revisions?)

I still think it might be a good idea to have the program save a Log (text) file while it's running that notes each step in the process and will give the user the possibility of seeing at which point(s) it encounters any problems/errors.  That might enable the user to figure out what they are doing wrong if it doesn't perform as expected or crashes.

I'd be very grateful if you can offer any suggestions that you think might enable me to get it running again.

Thanks.

**Comment by Highlander009** [comment]
PS: I didn't see your latest message until after I'd posted mine.  As I said, I tried it on a single folder with only ten videos + subs in it but still no joy!  I've checked the subs' integrity and they are all absolutely fine (the videos too).  I guess it must be something peculiar to my machine that's causing the problem.  If your revised version has the log file I'll try again and see if that throws any light on what the problem is here. :-( 
Maybe a log file will tell me exactly what is causing it to stop.
Thanks for taking the time to look.
Cheers.

**Comment by Highlander009** [comment]
One afterthought, I encode subs as UTF 8 with BOM (not just UTF 8 as many others do) that way the player connected to my TV (& the TV itself) will display characters like ♪ and ♫ rather than just a # to indicate music.  The subs then start with EF BB BF 31 0D 0A 30 hex rather than just 31 0D 0A 30 hex.  That wouldn't upset your program would it?

**Comment by Highlander009** [comment]
Hmmm, just tried it and wouldn't work with UTF 8 either! Grrrrrrrrrrrrrrr

**Comment by iPzard** [comment]
The security alert is expected, it's to allow Python's Flask microservices to interact with the program. Unfortunately, I don't have a batch script available, the code kind of pieces the commands together based on user options, feel free to take a look through if if you'd like: [mkvtoolnix.py](https://github.com/iPzard/mkvtoolnix-batch-tool/blob/master/resources/modules/mkvtoolnix.py)

Any chance you can zip and attach some of the subtitle files here? I can use them to test a few things on my end.

**Comment by Highlander009** [comment]
Hi,

Thanks for your reply.

I'm not a programmer, I just dabble, lol.

Windows batch scripts are the easiest for me to understand though even in them there are many commands, operators, arguments, and syntax that leave me completely confused! 🥴 lol.

I've found a (huge) batch script that appears to do what I want so as soon as I get the time I will attempt to modify that to carry out exactly what I want but I will keep an eye on any further developments in your own program to see if I can get it to work in the future; it would certainly be a great advantage if it were to offer some of the features I've mentioned previously like allowing (individual streams?) to be Default, Forced and Eng/Fre/Spa/Ger, etc. The ability to add Chapters (at fixed intervals?) would also be a great boon but perhaps the most important feature might be a process log allowing the user to track what's gone wrong (if anything does, lol).

In the meantime, please find attached an archive of the subs I have for the Doctor Who Series 11 videos I've been "testing" the program on.

[Doctor Who Series 11.zip](https://github.com/iPzard/mkvtoolnix-batch-tool/files/5666878/Doctor.Who.Series.11.zip)

Thanks, again, for your help.

Best Regards,
Brian Cameron.

**Comment by iPzard** [comment]
I see. When creating the app, I referenced the MKVToolNix CLI docs quite a bit, there's a lot of information there that may help with your batch script, [MKVToolNix Commands](https://mkvtoolnix.download/doc/mkvmerge.html). Thanks for attaching the subs! I'll look at these and see if I can pin-point your issue, a little busy lately but hopefully this weekend I get things resolved here.

**Comment by iPzard** [comment]
Well.. I tested the sub files on my end and everything is working like expected. Which is a confusing result, I was expecting some sort of error, but your idea about creating `.log` files for errors should help us get to the bottom of this, since I can have the program create a file w/the exact error _(I'll probably also include the command that created the error)_.. Will dig into that this weekend. I made this program to avoid exactly what you're trying to avoid.. manually merging each file

**Comment by Highlander009** [comment]
Thought it might also be useful to have some of the video material too so have attached the first 10 minutes of the first episode in the folder. 😊
(The appearance of the first female Doctor. 😉)

Oops!  10 minutes is too big it seems, lol. (So you won't see her after all, lol)

[01. The Woman Who Fell to Earth p06jcn8k original-00.00.00.000-00.02.09.039.zip](https://github.com/iPzard/mkvtoolnix-batch-tool/files/5667183/01.The.Woman.Who.Fell.to.Earth.p06jcn8k.original-00.00.00.000-00.02.09.039.zip)

**Comment by iPzard** [comment]
Haha no worries.. And awesome, yes this will definitely help! I'll try testing my merge(s) on that file, will help determine if there's an issue with the video+sub combination.

**Comment by Highlander009** [comment]
Incredible!!!!
I just downloaded the zip I sent you (I'd deleted it and its content after uploading it), unzipped the two files in it into a new folder (on the USB connected HDD where all the other videos were) and your program muxed them together perfectly! wtf!?
I'm gonna try again with the original files to see if it will work...
Will let you know what happens.

**Comment by iPzard** [comment]
Yea, worked for me too. Hmm.. I'm wondering if the original encoding of the video(s) is an issue. I'm guessing you used some tool to create that video snippet and it might have encoded it differently. Quick question, are you able to merge the original file and sub with MKVToolNix GUI, the original program that can't do batches? Trying to narrow down if the bug is in MKVToolNix or this app.

**Comment by Highlander009** [comment]
Jjings Crivens and help ma Boab!!! lol

It's now working perfectly on the original files too! (At least on a single folder anyway, The Series 11 one)

It now looks very much like the problem has been simply with my machine.  Perhaps the system restore(s) I implemented have fixed it?

I'm very sorry to have wasted your time on a problem that was not of your origin.

However, I did notice that one little glitch that may well need your attention: the program wouldn't allow me to drag/drop a folder onto the Destination field (think I already mentioned it?).
I suppose it's possible (likely now? 😕) that this "issue" may well be due to something not right on my PC again but it may be worth your while checking it out yourself to see whether it works for you (or asking somebody else using Win 10 to have a go at it)?

Maybe my other suggestions (especially the Log idea) would be of interest to you too?  So perhaps this hasn't been a **_complete_** waste of your time. 😌😉

I've started it running on the whole set (1 folder with 11 sub-folders; 167 videos in total) and currently it has (apparently) muxed over 60 0f them successfully.  Yayyyy! 😄

I'll let you know if completes successfully.

Cheers,
B.

**Comment by iPzard** [comment]
Hey, no worries! The important thing is you got it working. For drag/drop, that's only supported for the source folder. And definitely not a waste of time! Because now there will be a feature coming to create `.log` files for errors, which is still a great outcome ;)

**Comment by Highlander009** [comment]
Thanks, I'm glad you feel there's been some use in the exercise. 👍🏻😊

I'm also **_very_** pleased to confirm that the muxing of all the (167) videos has now completed (successfully as far as I can see so far; can't check 'em all individually but the ones I have checked appear fine).

So you can probably mark this "issue" as closed.
(Unless you wanted to leave it open for others to read as a **_warning_** to check that their own devices are working properly before harassing you with problems of their own making, lmao. 🤣)

Thanks again for all your assistance.

Stay safe &

Best Regards,
B.

**Comment by iPzard** [comment]
Very nice!!

**Comment by Highlander009** [comment]
Can I still reach you via this?

I wondered if I could get your help on something else I'm trying to do with these mkv files?

Could I explain the "issue" and send you some code that I am trying out to do what I want.  It's not very big and you could probably see/fix the problem I'm having in a flash, lol.

**Comment by iPzard** [comment]
Sure, feel free to paste it here, you can use the `<>` icon in the WYSIWYG to paste code.

**Comment by Highlander009** [comment]
Thanks.

I was just about to write it up when something more pressing came in and my attention got diverted but I've nearly completed that so I'll get back to you with details soon as I can,

B.

**Comment by Highlander009** [comment]
Hi Daniel,  (You might be more comfortable reading this in Word.  See the RedMe First.docx in the zip archive)

Thanks for taking the time to read this.

I am still able (thankfully) to use your program to mux together my videos & subs which is an enormous time saver for me!  Thank you again for that.  But there are a few other things I like to do when converting to MKVs.

I like to mark the subs as forced (so they come up automatically) and I also like to add chapters.  I also like to add a Title into the title field in the GUI (--title Movie/Episode Name) or, sometimes, put a blank space into that field.

Why the blank space?  Well, I mostly use VLC as a player and it displays the title for just less than five seconds at the start of every video.  If the title field is empty then it displays the filename (including the extension) instead but there are some videos where the dialogue (& hence the subs) appear earlier than 5 secs into the video. And, thus, are overwritten by the title/filename if it’s still onscreen! (This annoys the hell out of me; bit of a perfectionist, lol.)

Now, I’ve found another project called “mkvtoolnix-batch” which lets me set the Language, Forced yes/no and Default yes/no for each stream and also add chapters (in fixed 300s intervals) and I can also add a blank space into the title field for each video in a (single) folder (it doesn’t offer recursion).  Perhaps you could have a quick look at it?  It’s simple (& short) and easy enough even for me to understand, so you’ll grasp the principle of it very quickly, I’m sure, and if you know how it works it will make it easier for me to explain the rest of this, lol.  You can see it [here](https://github.com/Serede/mkvtoolnix-batch).

Now I’ve included two folders here, each with a couple of (the same) video clips in them and the files to use mkvtoolnix-batch on them. One video has a title in it and the other an empty title field (so displays the filename at the start).  The first folder (1 No Title) has mkvtoolnix-batch working perfectly to put a blank space into the title field (so nothing displays at the start, thus allowing subs to come up in under 5 secs if required).  If you d/click on mkvtoolnix-batch in that folder you will see the result.  I also included the original options.json file which I modified to suit my purposes and I’d be grateful if you would have a quick look at that too?  If you open the .rtf version of it you can see the changes I made.  Do you think the lines I Removed are likely to cause any problems?  (I took them out so they wouldn’t affect any other videos that they might not be ‘appropriate’ for, especially the display-dimensions).  Your comment(s) there would be much appreciated.

But the bigger problem I have is with the second folder (2 Episode Title) where I’d like the batch script to enter the “filename” (without the extension) of each *.mkv file into the title field.  Now, the optimal (?) way to do that would be (in my humble opinion) to pass the filename (less its extension) to the options.json file as each *.mkv file is being processed but, despite spending hours searching for a way to do that on the web, I still have no clue as to whether that is even possible!

So I tried a different approach as you’ll see if you look into the mkvtoolnix-batch.bat file in there.  I saw something that said %~nI would capture the filename (- .ext) in a batch file but when I do that the program runs OK but just writes %~nI into the title field of each video.  So I tried using %~nf but, although it does capture the filenames, that just seems to corrupt the loop counter and the writes fail completely.  Have a go yourself (just edit the bat file to replace %~nI with %~nf, I’ve turned echo off so the process displays).  You can run the batch files in both folders with impunity because the original clips are untouched (as any output goes into a new folder which you can just delete after viewing its content if you want to try something different.)

I hope I’ve explained all this clearly enough?

Do you know of any way to successfully pass the filename (- .mkv) to the json file as each *.mkv file gets processed (that would mean no alteration of the batch file was needed); is it even possible?

Or can you fix my edited batch file so that it uses the correct ‘entry’ for each *.mkv as it re-writes them?

Any help you can offer would be greatly appreciated.

Thanks again,
Brian.
[mkvtoolnix-batch (Changing things in muxed mkv).zip](https://github.com/iPzard/mkvtoolnix-batch-tool/files/5675611/mkvtoolnix-batch.Changing.things.in.muxed.mkv.zip)

**Comment by iPzard** [comment]
Let me take some time to digest all this, turns out this week is super busy but will update here ASAP.  Might even be worth adding some of those features to this tool later, but will see if I can help you get up and running before that.

**Comment by Highlander009** [comment]
Please don't waste any time on it.  I thought it might be something you would immediately know an answer to but, if not, I don't want you to be distracted from your own work.  I'm sure there's a simple solution available in batch scripting but that may not be an area of expertise for you.  Thanks.

**Comment by iPzard** [comment]
Ok, sound good. Yea, I'm definitely not a batch script (.bat) expert or anything haha.
