### ISSUE TITLE
Why does this tool need Internet access?

### ISSUE THREAD

**Issue by Sawtaytoes** [iPzard/mkvtoolnix-batch-tool#94]
When opening the tool, it asked for access to my firewall. Why is the tool phoning anywhere online?

I'm already skeptical about using new tools, but now I'm more skeptical why it's connecting anywhere.

**Comment by iPzard** [comment]
This is to access localhost in order to use Python w/Flask as a backend for services on the PC.

**Comment by Sawtaytoes** [comment]
Thanks for clarifying!
