### ISSUE TITLE
ASS to SRT converting

### ISSUE THREAD

**Issue by gelsas** [iPzard/mkvtoolnix-batch-tool#96]
Hi,

After encoding my whole library with handbrake all my subtitles are not ASS, would it be possible that you add a feature to convert all ASS Subtitles inside the mkvs to SRT. 

Would really need a solution that can process it automatically for me instead of me doing it manually

**Comment by iPzard** [comment]
Have you tried exporting them with the tool, then re-adding? I think it will export them to srt, but not entirely sure off the top of my head. 

Be sure to make a back up of your files first.
